import type { Metadata } from "next";
import "../../globals.css"
import AuthNav from "./components/AuthNav";
import AuthFooter from "./components/AuthFooter";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <div className="min-h-full flex flex-col">
      <AuthNav />
      {children}
      <AuthFooter />
    </div>
  );
}
