import type { Metadata } from "next";
<<<<<<< HEAD
// import "/globals.css";

=======
import "../../globals.css"
>>>>>>> baebac0b2c167aad6aceeaa3bb2523c939ff2b1c
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    // <html
    //   lang="en"
    //   className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    // >
    //   <body className="min-h-full flex flex-col">{children}</body>
    // </html>
    <div className="min-h-full flex flex-col">
      {children}
    </div>
  );
}
