// // app/layout.tsx
// import type { Metadata } from "next";
// import { Inter, Playfair_Display } from "next/font/google";
// import "./globals.css";

// // Body / Price font
// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
//   display: "swap",
// });

// // Premium Header font
// const playfair = Playfair_Display({
//   subsets: ["latin"],
//   variable: "--font-playfair",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Premium Marketplace",
//   description: "Curated high-end goods",
// };


// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${inter.variable} ${playfair.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import { Inter, Playfair_Display } from "next/font/google";
// import "./globals.css";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
//   display: "swap",
// });

// const playfair = Playfair_Display({
//   subsets: ["latin"],
//   variable: "--font-playfair",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Premium Marketplace",
//   description: "Curated high-end goods",
// };

// interface RootLayoutProps {
//   children: React.ReactNode;
// }

// export default function RootLayout(props: RootLayoutProps) {
//   return (
//     <html
//       lang="en"
//       className={`${inter.variable} ${playfair.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{props.children}</body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     // <html
//     //   lang="en"
//     //   className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     // >
//     //   <body className="min-h-full flex flex-col">{children}</body>
//     // </html>
//     <div className="min-h-full flex flex-col">
//       {children}
//     </div>
//   );
// }
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}